Fix setup.py failing because of incorrect README name
The README file was renamed from "README.rst" to "readme.md" in
368dedff9c03ea234962a789b5b60d5a0670cd22 but its usages were not all
replaced, leading to

    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

when trying to `pip install` the module.