Fix REPL exiting when keywords have no shortdoc
The `keywords` command failed when there were keywords which don't have
a shortdoc, causing the REPL to exit and the logs to show

    AttributeError: 'KeywordDoc' object has no attribute 'hasattr'

This change fixes that by only printing the shortdoc if there is one
defined for the keyword.